#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."

cat > .env <<'EOF'
APP_NAME=app-deploy
APP_ENV=dev
FRONTEND_PORT=3000
BACKEND_PORT=8000
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=idp_portal
POSTGRES_USER=idp_user
POSTGRES_PASSWORD=change_me
BOLT_PROVIDER=PLACEHOLDER
BOLT_PROJECT_NAME=PLACEHOLDER
BOLT_API_KEY=PLACEHOLDER
GITHUB_ORG=PLACEHOLDER
GITHUB_TOKEN=PLACEHOLDER
IMAGE_REGISTRY=PLACEHOLDER
IMAGE_NAMESPACE=PLACEHOLDER
ARGOCD_SERVER=PLACEHOLDER
VAULT_ADDR=PLACEHOLDER
EOF

echo ".env created with placeholders"
